FROM node:20-alpine

WORKDIR /app-client

COPY ./client/package.json /app-client/package.json
COPY ./client/package-lock.json /app-client/package-lock.json

RUN npm install --legacy-peer-deps

COPY ./client /app-client

EXPOSE 3000

CMD ["npm", "run", "dev"]
