version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8000
      DB_URI: mongodb://mongodb:27017/syncronify
    depends_on:
      - mongodb
      - cache
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
volumes:
  mongodb-data:
  cache: